#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

RUN_FOLDER=/var/tmp/tdxtest/

install_deps() {
  sudo apt install -y python3-pip python3-venv
}

setup_venv() {
  deactivate &> /dev/null || true
  python3 -m venv ${RUN_FOLDER}/venv
  source ${RUN_FOLDER}/venv/bin/activate
  python3 -m pip install paramiko \
	  pytest \
	  parameterized \
	  py-cpuinfo

  (cd ${SCRIPT_DIR}/lib/tdx-tools/ && python3 -m pip install ./)
}

export PYTHONPATH=$PYTHONPATH:${SCRIPT_DIR}/lib

echo "Install dependencies ..."
install_deps &> /dev/null
echo "Setup test environment ..."
setup_venv &> /dev/null

# TODO: -rP, -rE : print test output on Passed and Error
# -s : do not capture logs
# -v : increase verbosity
python3 -m pytest -s -v --junitxml=report.xml "$@"
