#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
CHECKBOX_DIR=${SCRIPT_DIR}/checkbox

echo "Not supported yet"
exit 1

install_deps() {
		sudo snap install checkbox22 &> /de
		sudo snap install checkbox --classic
}

install_deps &> /dev/null

rm -rf /var/tmp/checkbox-providers/checkbox-provider-tdx/
cp -rf ${CHECKBOX_DIR}/checkbox-provider-tdx /var/tmp/checkbox-providers/
cp -rf ${SCRIPT_DIR}/bin /var/tmp/checkbox-providers/checkbox-provider-tdx
cp -rf ${SCRIPT_DIR}/lib /var/tmp/checkbox-providers/checkbox-provider-tdx

# run checkbox in side-provider mode and use the host system python3 libraries
# checkbox comes with its own python libs and runtime (see checkbox22)
# check the requirement

PATH=$PATH:${CHECKBOX_DIR}/bin ${CHECKBOX_DIR}/bin/test-runner-automated
