#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
CHECKBOX_DIR=${SCRIPT_DIR}/checkbox

install_deps() {
		sudo snap install checkbox22 &> /de
		sudo snap install checkbox --classic
}

install_deps &> /dev/null

rm -rf /var/tmp/checkbox-providers/checkbox-provider-tdx/
mkdir -p /var/tmp/checkbox-providers
cp -rf ${CHECKBOX_DIR}/checkbox-provider-tdx /var/tmp/checkbox-providers/
cp -rf ${SCRIPT_DIR}/pytest /var/tmp/checkbox-providers/checkbox-provider-tdx/bin
cp -rf ${SCRIPT_DIR}/lib /var/tmp/checkbox-providers/checkbox-provider-tdx
chmod a+x /var/tmp/checkbox-providers/checkbox-provider-tdx/bin/*

# run checkbox in side-provider mode and use the host system python3 libraries
# checkbox comes with its own python libs and runtime (see checkbox22)
# check the requirement

PATH=$PATH:${CHECKBOX_DIR}/bin ${CHECKBOX_DIR}/bin/test-runner-automated

# Reports for checkbox get put here
echo "Reports can be found at /var/tmp/tdxtest/reports"
