#!/bin/bash

RUN_FOLDER=/var/tmp/tdxtest/
CHECKBOX_FOLDER=/var/tmp/checkbox-providers/checkbox-provider-tdx/

setup_venv() {
  mkdir -p ${RUN_FOLDER}
  python3 -m venv ${RUN_FOLDER}/venv
  source ${RUN_FOLDER}/venv/bin/activate
  python3 -m pip install paramiko==3.3.1 \
	  pytest==8.2.1 \
	  parameterized==0.9.0 \
	  py-cpuinfo==9.0.0

  (cd ${CHECKBOX_FOLDER}/lib/tdx-tools/ && python3 -m pip install ./)
}

deactivate &> /dev/null || true
if [ ! -d ${RUN_FOLDER}/venv ]; then
  setup_venv &> /dev/null
else
  source ${RUN_FOLDER}/venv/bin/activate
fi

export PYTHONPATH=${PYTHONPATH}:${CHECKBOX_FOLDER}/lib
python3 ${CHECKBOX_FOLDER}/bin/$1
